project_id = "iokkwxjkvzgstkkbwnoa"

[functions.nasa-firms]
verify_jwt = false

[functions.calculate-flight-emission]
verify_jwt = false

[functions.flight-emissions]
verify_jwt = false

[functions.map-data]
verify_jwt = false
